import type { GrowProgram } from '../types/farmModule';

/**
 * Built-in grow program presets for common microgreens.
 * These are the canonical recipes — users can clone and customize.
 */
export const GROW_PROGRAM_PRESETS: Record<string, GrowProgram> = {
  broccoli_10day: {
    id: 'broccoli_10day',
    name: 'Broccoli Microgreens — 10 Day',
    cropType: 'broccoli_microgreens',
    description: 'Classic broccoli microgreens. Soak seeds 8-12h, expect harvest at day 10.',
    totalDays: 10,
    isPreset: true,
    stages: [
      {
        name: 'Seeding', type: 'seeding', dayStart: 1, dayEnd: 2,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 30, frequencySeconds: 7200, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 60, humidityMax: 80, coverTrays: true },
        checklist: ['Soak seeds 8-12h', 'Spread evenly on moist medium', 'Cover with dome/weight'],
      },
      {
        name: 'Germination', type: 'germination', dayStart: 3, dayEnd: 4,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 45, frequencySeconds: 10800, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 68, tempMaxF: 75, humidityMin: 65, humidityMax: 80, coverTrays: true },
        checklist: ['Check for sprouts', 'Maintain moisture', 'Keep covered'],
      },
      {
        name: 'Blackout', type: 'blackout', dayStart: 5, dayEnd: 6,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 55, humidityMax: 70, coverTrays: false },
        checklist: ['Remove cover/dome', 'Keep in dark', 'Stems will elongate'],
      },
      {
        name: 'Light Exposure', type: 'light_exposure', dayStart: 7, dayEnd: 8,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 20 },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 50, humidityMax: 65 },
        checklist: ['Introduce grow lights', 'Leaves will green up', 'Monitor soil moisture'],
      },
      {
        name: 'Growth', type: 'growth', dayStart: 9, dayEnd: 9,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 21600, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 22 },
        environment: { tempMinF: 65, tempMaxF: 72, humidityMin: 50, humidityMax: 60 },
        checklist: ['Full growth phase', 'Monitor density', 'Check for mold'],
      },
      {
        name: 'Pre-Harvest', type: 'pre_harvest', dayStart: 10, dayEnd: 10,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 28800, startTime: '06:00', endTime: '18:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 18 },
        environment: { tempMinF: 62, tempMaxF: 70, humidityMin: 45, humidityMax: 55 },
        checklist: ['Reduce watering', 'Firm up stems', 'Prepare for harvest'],
      },
    ],
  },
  radish_8day: {
    id: 'radish_8day',
    name: 'Radish Microgreens — 8 Day',
    cropType: 'radish',
    description: 'Fast-growing radish microgreens. No pre-soak needed.',
    totalDays: 8,
    isPreset: true,
    stages: [
      {
        name: 'Seeding', type: 'seeding', dayStart: 1, dayEnd: 1,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 30, frequencySeconds: 7200, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 60, tempMaxF: 70, humidityMin: 60, humidityMax: 75, coverTrays: true },
        checklist: ['No pre-soak needed', 'Press seeds into medium', 'Cover with weight'],
      },
      {
        name: 'Germination', type: 'germination', dayStart: 2, dayEnd: 3,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 45, frequencySeconds: 10800, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 62, tempMaxF: 70, humidityMin: 60, humidityMax: 75, coverTrays: true },
        checklist: ['Watch for rapid germination', 'Keep moist', 'Remove weight when lifting'],
      },
      {
        name: 'Blackout', type: 'blackout', dayStart: 4, dayEnd: 4,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 60, tempMaxF: 68, humidityMin: 55, humidityMax: 65 },
        checklist: ['Remove cover', 'Keep dark', 'Short blackout — stems push up'],
      },
      {
        name: 'Light Exposure', type: 'light_exposure', dayStart: 5, dayEnd: 6,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 20 },
        environment: { tempMinF: 60, tempMaxF: 68, humidityMin: 50, humidityMax: 60 },
        checklist: ['Introduce lights', 'Leaves unfurl', 'Color develops'],
      },
      {
        name: 'Growth', type: 'growth', dayStart: 7, dayEnd: 7,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 21600, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 22 },
        environment: { tempMinF: 60, tempMaxF: 65, humidityMin: 45, humidityMax: 55 },
        checklist: ['Watch for true leaves = harvest soon'],
      },
      {
        name: 'Pre-Harvest', type: 'pre_harvest', dayStart: 8, dayEnd: 8,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 28800, startTime: '06:00', endTime: '18:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 18 },
        environment: { tempMinF: 58, tempMaxF: 65, humidityMin: 40, humidityMax: 50 },
        checklist: ['Ready when cotyledons fully open', 'Reduce water', 'Harvest cut'],
      },
    ],
  },
  sunflower_12day: {
    id: 'sunflower_12day',
    name: 'Sunflower Microgreens — 12 Day',
    cropType: 'sunflower',
    description: 'Large, crunchy sunflower shoots. Soak seeds 12h, use weight.',
    totalDays: 12,
    isPreset: true,
    stages: [
      {
        name: 'Seeding', type: 'seeding', dayStart: 1, dayEnd: 2,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 30, frequencySeconds: 7200, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 68, tempMaxF: 78, humidityMin: 65, humidityMax: 80, coverTrays: true },
        checklist: ['Soak seeds 12h', 'Place weight on top', 'Heavy watering'],
      },
      {
        name: 'Germination', type: 'germination', dayStart: 3, dayEnd: 4,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 7200, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 70, tempMaxF: 78, humidityMin: 65, humidityMax: 80, coverTrays: true },
        checklist: ['Remove weight on day 3', 'Heavy seeds need more water', 'Keep covered'],
      },
      {
        name: 'Blackout', type: 'blackout', dayStart: 5, dayEnd: 7,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 10800, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 68, tempMaxF: 78, humidityMin: 55, humidityMax: 70 },
        checklist: ['Long blackout period', 'Stems reach 3-4 inches', 'Keep dark'],
      },
      {
        name: 'Light Exposure', type: 'light_exposure', dayStart: 8, dayEnd: 9,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 120, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 20 },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 50, humidityMax: 65 },
        checklist: ['Leaves open up', 'Help shed remaining hulls', 'Green up begins'],
      },
      {
        name: 'Growth', type: 'growth', dayStart: 10, dayEnd: 11,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 120, frequencySeconds: 21600, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 22 },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 50, humidityMax: 60 },
        checklist: ['Full growth', 'Thick stems developing', 'Watch for mold'],
      },
      {
        name: 'Pre-Harvest', type: 'pre_harvest', dayStart: 12, dayEnd: 12,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 28800, startTime: '06:00', endTime: '18:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 18 },
        environment: { tempMinF: 62, tempMaxF: 72, humidityMin: 45, humidityMax: 55 },
        checklist: ['Harvest before true leaves appear', 'Cut at soil level'],
      },
    ],
  },
  basil_14day: {
    id: 'basil_14day',
    name: 'Basil Microgreens — 14 Day',
    cropType: 'basil',
    description: 'Slow-growing aromatic basil. Mucilaginous seeds — mist, do not soak.',
    totalDays: 14,
    isPreset: true,
    stages: [
      {
        name: 'Seeding', type: 'seeding', dayStart: 1, dayEnd: 3,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 30, frequencySeconds: 7200, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 72, tempMaxF: 82, humidityMin: 65, humidityMax: 80, coverTrays: true },
        checklist: ['Do NOT soak — mucilaginous seeds', 'Mist onto moist medium', 'Cover with dome'],
      },
      {
        name: 'Germination', type: 'germination', dayStart: 4, dayEnd: 6,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 45, frequencySeconds: 10800, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 72, tempMaxF: 82, humidityMin: 65, humidityMax: 80, coverTrays: true },
        checklist: ['Slow germinator — be patient', 'Keep warm', 'Maintain humidity'],
      },
      {
        name: 'Blackout', type: 'blackout', dayStart: 7, dayEnd: 8,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 70, tempMaxF: 80, humidityMin: 55, humidityMax: 70 },
        checklist: ['Short stems — keep warm', 'Remove cover'],
      },
      {
        name: 'Light Exposure', type: 'light_exposure', dayStart: 9, dayEnd: 10,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 20 },
        environment: { tempMinF: 70, tempMaxF: 82, humidityMin: 50, humidityMax: 65 },
        checklist: ['Introduce grow lights', 'Leaves green up', 'Aromatic oils developing'],
      },
      {
        name: 'Growth', type: 'growth', dayStart: 11, dayEnd: 12,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 21600, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 22 },
        environment: { tempMinF: 70, tempMaxF: 80, humidityMin: 50, humidityMax: 60 },
        checklist: ['Full aroma development', 'Monitor for mold', 'Beautiful purple-green color'],
      },
      {
        name: 'Pre-Harvest', type: 'pre_harvest', dayStart: 13, dayEnd: 14,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 28800, startTime: '06:00', endTime: '18:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 18 },
        environment: { tempMinF: 68, tempMaxF: 78, humidityMin: 45, humidityMax: 55 },
        checklist: ['Harvest at first true leaf', 'Reduce water', 'Maximum flavor'],
      },
    ],
  },
  arugula_10day: {
    id: 'arugula_10day',
    name: 'Arugula Microgreens — 10 Day',
    cropType: 'arugula',
    description: 'Peppery arugula microgreens. Quick germination, easy grower.',
    totalDays: 10,
    isPreset: true,
    stages: [
      {
        name: 'Seeding', type: 'seeding', dayStart: 1, dayEnd: 2,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 30, frequencySeconds: 7200, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 60, tempMaxF: 70, humidityMin: 60, humidityMax: 75, coverTrays: true },
        checklist: ['Light surface sow', 'Mist gently', 'Cover with dome'],
      },
      {
        name: 'Germination', type: 'germination', dayStart: 3, dayEnd: 4,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 45, frequencySeconds: 10800, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 60, tempMaxF: 70, humidityMin: 55, humidityMax: 70, coverTrays: true },
        checklist: ['Fast germinator', 'Watch for dense coverage', 'Keep moist'],
      },
      {
        name: 'Blackout', type: 'blackout', dayStart: 5, dayEnd: 5,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 58, tempMaxF: 68, humidityMin: 50, humidityMax: 65 },
        checklist: ['Remove cover', 'Short blackout', 'Stems push up'],
      },
      {
        name: 'Light Exposure', type: 'light_exposure', dayStart: 6, dayEnd: 7,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 20 },
        environment: { tempMinF: 58, tempMaxF: 68, humidityMin: 45, humidityMax: 60 },
        checklist: ['Introduce light', 'Leaves develop', 'Peppery flavor emerging'],
      },
      {
        name: 'Growth', type: 'growth', dayStart: 8, dayEnd: 9,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 90, frequencySeconds: 21600, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 22 },
        environment: { tempMinF: 58, tempMaxF: 65, humidityMin: 45, humidityMax: 55 },
        checklist: ['Full growth', 'Strong peppery bite developing'],
      },
      {
        name: 'Pre-Harvest', type: 'pre_harvest', dayStart: 10, dayEnd: 10,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 28800, startTime: '06:00', endTime: '18:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 18 },
        environment: { tempMinF: 55, tempMaxF: 65, humidityMin: 40, humidityMax: 50 },
        checklist: ['Harvest at first true leaf', 'Best peppery flavor now'],
      },
    ],
  },
  chia_10day: {
    id: 'chia_10day',
    name: 'Chia Microgreens — 10 Day',
    cropType: 'chia',
    description: 'Mucilaginous chia seeds. Mist only, do not soak. High humidity required.',
    totalDays: 10,
    isPreset: true,
    stages: [
      {
        name: 'Seeding', type: 'seeding', dayStart: 1, dayEnd: 2,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 20, frequencySeconds: 5400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 65, humidityMax: 85, coverTrays: true },
        checklist: ['Do NOT soak — mucilaginous', 'Sprinkle on wet medium', 'Mist heavily', 'Cover with dome'],
      },
      {
        name: 'Germination', type: 'germination', dayStart: 3, dayEnd: 4,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 30, frequencySeconds: 7200, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 65, humidityMax: 85, coverTrays: true },
        checklist: ['Gel coating is normal', 'Keep very humid', 'Tiny sprouts emerging'],
      },
      {
        name: 'Blackout', type: 'blackout', dayStart: 5, dayEnd: 6,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 45, frequencySeconds: 10800, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: false },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 60, humidityMax: 75 },
        checklist: ['Remove dome', 'Keep dark', 'Delicate stems elongating'],
      },
      {
        name: 'Light Exposure', type: 'light_exposure', dayStart: 7, dayEnd: 8,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 14400, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 20 },
        environment: { tempMinF: 65, tempMaxF: 75, humidityMin: 55, humidityMax: 70 },
        checklist: ['Introduce light', 'Leaves green up', 'Gentle watering only'],
      },
      {
        name: 'Growth', type: 'growth', dayStart: 9, dayEnd: 9,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 60, frequencySeconds: 21600, startTime: '06:00', endTime: '22:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 22 },
        environment: { tempMinF: 65, tempMaxF: 72, humidityMin: 50, humidityMax: 65 },
        checklist: ['Full green growth', 'Monitor for mold — high risk'],
      },
      {
        name: 'Pre-Harvest', type: 'pre_harvest', dayStart: 10, dayEnd: 10,
        schedules: [{ targetSubtype: 'pump', durationSeconds: 45, frequencySeconds: 28800, startTime: '06:00', endTime: '18:00' }],
        lighting: { enabled: true, onHour: 6, offHour: 18 },
        environment: { tempMinF: 62, tempMaxF: 70, humidityMin: 45, humidityMax: 55 },
        checklist: ['Harvest when 2-3 inches tall', 'Very delicate — handle gently'],
      },
    ],
  },
};
